spring:
  data:
    mongodb:
      database: transfer-service
      port: 27017

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

my:
  property: hello from config server