spring:
  cloud:
    gateway:
      routes:
        - id: authService
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: userService
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - JwtTokenFilter
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
jwt:
  secret: transfer
  expired: 3600000